query GetUsers {
  users {
    uid
    firstName
    lastName
    email
    country
    createdAt
  }
}


query GetAthleteResumes {
  athleteResumes {
    gender
    sport
    updatedAt
  }
}
query GetUserAthleteResume($userId: UUID!) {
  athleteResumes(where: { userId: { eq: $userId } }) {
    id
    gender
    sport
    parameters
    updatedAt
  }
}
