extend type Mutation {
  """
  ✨ Insert a single `AthleteResume` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  athleteResume_insert(
    """
    Data object to insert into the table.
    """
    data: AthleteResume_Data!
  ): AthleteResume_KeyOutput! @fdc_generated(from: "AthleteResume", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AthleteResume` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  athleteResume_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AthleteResume_Data!]!
  ): [AthleteResume_KeyOutput!]! @fdc_generated(from: "AthleteResume", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AthleteResume` into the table, based on the primary key. Returns the key of the newly inserted `AthleteResume`.
  """
  athleteResume_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AthleteResume_Data!
  ): AthleteResume_KeyOutput! @fdc_generated(from: "AthleteResume", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AthleteResume` objects into the table, based on the primary key. Returns the key of the newly inserted `AthleteResume`.
  """
  athleteResume_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AthleteResume_Data!]!
  ): [AthleteResume_KeyOutput!]! @fdc_generated(from: "AthleteResume", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AthleteResume` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  athleteResume_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AthleteResume_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AthleteResume_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AthleteResume_Data!
  ): AthleteResume_KeyOutput @fdc_generated(from: "AthleteResume", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AthleteResume` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  athleteResume_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AthleteResume_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AthleteResume_Data!
  ): Int! @fdc_generated(from: "AthleteResume", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AthleteResume` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  athleteResume_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AthleteResume_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AthleteResume_FirstRow
  ): AthleteResume_KeyOutput @fdc_generated(from: "AthleteResume", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AthleteResume` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  athleteResume_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AthleteResume_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AthleteResume", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
