/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=f29f1251&sid=76ef0176
 */
import * as React from "react";
import { NavLinkProps } from "../types";

export const NavLink: React.FC<NavLinkProps> = ({ text, width }) => (
  <div className={`self-stretch my-auto ${width}`}>{text}</div>
);
