/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=f29f1251&sid=76ef0176
 */
import * as React from "react";
import { SignUpButtonProps } from "../types";

export const SignUpButton: React.FC<SignUpButtonProps> = ({ text }) => (
  <button
    className="px-6 py-2.5 border-2 border-black border-solid rounded-[100px] max-md:px-5"
    type="button"
  >
    {text}
  </button>
);
