/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=f29f1251&sid=76ef0176
 */
export interface NavLinkProps {
  text: string;
  width: string;
}

export interface SignUpButtonProps {
  text: string;
}
