type User @table {
  id: UUID! @default(expr: "uuidV4()")
  uid: String! @unique
  firstName: String!
  lastName: String!
  email: String! @unique
  country: String
  createdAt: Timestamp! @default(expr: "request.time") # Use request time instead of now()
}

type AthleteResume @table {
  id: UUID! @default(expr: "uuidV4()")
  userId: UUID!
  gender: String!
  sport: String!
  parameters: [String]! # Array for sport-specific parameters
  updatedAt: Timestamp! @default(expr: "request.time") # Use request time
}
